# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 477fb259b070ac0add9910504fed0ec3ec889ed8a93c42b8e8c1c394637af5326e4fd59fa3a8bfba9a1801f5005b5108475ba0d1fff987cbe26c733f2bb66cb1

test:
  secret_key_base: cdc16579e511aaa485b6e0425f6683a726ac14b1462c5362be4e6b586bd96a4eb0a19495ca18fe77c9f70a5cbbfea33408cb2669873a5df369ecd21ccc86802a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
